'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';

/**
 * Hardened Cron Wrapper Generator
 * Composes flock (single-instance) + timeout (bounded runtime) + retry
 * (exponential backoff) + logging + failure alert into one wrapper script
 * and a ready-to-paste crontab line. No props, no external state.
 *
 * The generated bash follows the BashSnippets standard:
 *   set -euo pipefail, CHECK/CROSS defined before use, comments explain WHY.
 *
 * Contract: `command` is a single command with arguments. For a pipeline or
 * multiple commands, the user wraps them in  bash -c '...'  themselves — this
 * is surfaced in the UI, because timeout/retry only bound the launched process.
 */

type LockMode = 'skip' | 'wait';
type OutputTab = 'wrapper' | 'crontab';

const SECTION =
  'border border-[var(--border)] rounded-[var(--radius)] bg-[var(--bg2)] p-4';
const LABEL =
  'font-[family-name:var(--font-mono)] text-sm text-[var(--text)]';
const HINT = 'text-xs text-[var(--muted)] mt-1 leading-relaxed';
const INPUT =
  'w-full mt-2 px-3 py-2 rounded-[var(--radius)] bg-[var(--bg)] border border-[var(--border)] ' +
  'text-[var(--text)] font-[family-name:var(--font-mono)] text-sm ' +
  'focus:outline-none focus:border-[var(--green)] transition-colors';

function slugifyName(cmd: string): string {
  const first = cmd.trim().split(/\s+/)[0] || 'job';
  const base = first.split('/').pop() || 'job';
  const cleaned = base.replace(/[^a-zA-Z0-9_-]/g, '').toLowerCase();
  return cleaned || 'job';
}

function Toggle({
  on,
  onChange,
  label,
}: {
  on: boolean;
  onChange: (v: boolean) => void;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={() => onChange(!on)}
      aria-pressed={on}
      className="flex items-center gap-3 w-full text-left group"
    >
      <span
        className={
          'relative inline-flex h-5 w-9 shrink-0 rounded-full transition-colors ' +
          (on ? 'bg-[var(--green-dim)]' : 'bg-[var(--bg3)]') +
          ' border ' +
          (on ? 'border-[var(--green)]' : 'border-[var(--border)]')
        }
      >
        <span
          className={
            'absolute top-1/2 -translate-y-1/2 h-3.5 w-3.5 rounded-full transition-all ' +
            (on
              ? 'left-[18px] bg-[var(--green)]'
              : 'left-[3px] bg-[var(--muted)]')
          }
        />
      </span>
      <span
        className={
          'font-[family-name:var(--font-heading)] text-base ' +
          (on ? 'text-[var(--text)]' : 'text-[var(--muted)]')
        }
      >
        {label}
      </span>
    </button>
  );
}

export default function CronWrapperGenerator() {
  const [command, setCommand] = useState('rsync -a --delete /data/ /mnt/backup/data/');
  const [name, setName] = useState('');

  const [lockOn, setLockOn] = useState(true);
  const [lockMode, setLockMode] = useState<LockMode>('skip');
  const [waitSeconds, setWaitSeconds] = useState('30');

  const [timeoutOn, setTimeoutOn] = useState(true);
  const [maxRuntime, setMaxRuntime] = useState('5m');
  const [killGrace, setKillGrace] = useState('20s');

  const [retryOn, setRetryOn] = useState(false);
  const [maxAttempts, setMaxAttempts] = useState('5');
  const [baseDelay, setBaseDelay] = useState('1');

  const [logOn, setLogOn] = useState(true);
  const [logPath, setLogPath] = useState('');

  const [alertOn, setAlertOn] = useState(false);
  const [email, setEmail] = useState('ops@example.com');

  const [schedule, setSchedule] = useState('*/5 * * * *');

  const [tab, setTab] = useState<OutputTab>('wrapper');
  const [copied, setCopied] = useState<string | null>(null);

  const jobName = (name.trim() || slugifyName(command)).replace(
    /[^a-zA-Z0-9_-]/g,
    '',
  ) || 'job';
  const effLogPath = logPath.trim() || `/var/log/${jobName}.log`;
  const lockFile = `/run/lock/${jobName}.lock`;
  const wrapperPath = `/usr/local/bin/safe-${jobName}.sh`;

  // --- wrapper script generation -------------------------------------------
  const wrapper = useMemo(() => {
    const cmd = command.trim() || 'echo "set a command first"';
    const L: string[] = [];
    const guards = [
      lockOn && 'single-instance',
      timeoutOn && 'time-bounded',
      retryOn && 'retried',
    ]
      .filter(Boolean)
      .join(', ');

    L.push('#!/bin/bash');
    L.push(`# Script: safe-${jobName}.sh`);
    L.push(`# Purpose: Run a cron job safely${guards ? ' — ' + guards : ''}`);
    L.push('# Generated by https://bashsnippets.xyz/tools/cron-wrapper-generator');
    L.push('# Note: the command is a single command + args. For a pipeline,');
    L.push("#       set the command to:  bash -c 'cmd1 | cmd2'");
    L.push('set -euo pipefail');
    L.push('');
    L.push('CHECK="✓"');
    L.push('CROSS="✗"');
    L.push('');

    if (logOn) L.push(`LOG="${effLogPath}"`);
    if (lockOn) L.push(`LOCK_FILE="${lockFile}"`);
    if (logOn || lockOn) L.push('');

    // log() — to file if logging is on, else to stdout (cron captures it)
    if (logOn) {
      L.push("log() { echo \"$(date '+%F %T') $*\" >> \"$LOG\"; }");
    } else {
      L.push("log() { echo \"$(date '+%F %T') $*\"; }");
    }
    L.push('');

    // run() — the command, optionally bounded by timeout
    L.push('run() {');
    if (timeoutOn) {
      L.push('    # SIGTERM at MAX_RUNTIME; SIGKILL KILL_GRACE later if ignored.');
      L.push(`    timeout -k ${killGrace} ${maxRuntime} ${cmd}`);
    } else {
      L.push(`    ${cmd}`);
    }
    L.push('}');
    L.push('');

    // retry() — exponential backoff with jitter
    if (retryOn) {
      L.push('# Retry with exponential backoff and jitter.');
      L.push('retry() {');
      L.push('    local max_attempts="$1"; shift');
      L.push('    local attempt=1');
      L.push(`    local delay=${baseDelay || '1'}   # base delay, doubles each round`);
      L.push('    local max_delay=30                # cap so backoff never runs away');
      L.push('    until "$@"; do');
      L.push('        if (( attempt >= max_attempts )); then return 1; fi');
      L.push('        local pause=$(( delay + RANDOM % 3 ))  # 0-2s jitter');
      L.push('        log "$CROSS attempt $attempt failed — retrying in ${pause}s"');
      L.push('        sleep "$pause"');
      L.push('        attempt=$(( attempt + 1 ))');
      L.push('        delay=$(( delay * 2 ))');
      L.push('        if (( delay > max_delay )); then delay=$max_delay; fi');
      L.push('    done');
      L.push('}');
      L.push('');
    }

    // main()
    L.push('main() {');
    if (lockOn) {
      const flockFlag = lockMode === 'wait' ? `-w ${waitSeconds || '30'}` : '-n';
      L.push('    # Lock lives on the open descriptor; kernel frees it on exit.');
      L.push('    exec 200>"$LOCK_FILE"');
      L.push(`    if ! flock ${flockFlag} 200; then`);
      L.push('        log "$CROSS previous run still active — skipping"');
      L.push('        exit 0');
      L.push('    fi');
      L.push('    log "$CHECK lock acquired"');
      L.push('');
    }

    const invoke = retryOn ? `retry ${maxAttempts || '5'} run` : 'run';
    L.push(`    if ${invoke}; then`);
    L.push('        log "$CHECK completed"');
    L.push('    else');
    L.push('        log "$CROSS failed"');
    if (alertOn) {
      const ref = logOn ? ' See $LOG.' : '';
      L.push(
        `        printf '%s\\n' "${jobName} failed on $(hostname) at $(date '+%F %T').${ref}" \\`,
      );
      L.push(`            | mailx -s "[cron] ${jobName} failed on $(hostname)" ${email.trim() || 'ops@example.com'}`);
    }
    L.push('        exit 1');
    L.push('    fi');
    L.push('}');
    L.push('');
    L.push('main "$@"');

    return L.join('\n');
  }, [
    command,
    jobName,
    lockOn,
    lockFile,
    lockMode,
    waitSeconds,
    timeoutOn,
    maxRuntime,
    killGrace,
    retryOn,
    maxAttempts,
    baseDelay,
    logOn,
    effLogPath,
    alertOn,
    email,
  ]);

  // --- crontab line generation ---------------------------------------------
  const crontab = useMemo(() => {
    const sched = schedule.trim() || '# schedule';
    // If retry or alert is on, those need the wrapper — point cron at it.
    const needsWrapper = retryOn || alertOn;
    if (needsWrapper) {
      return `${sched} ${wrapperPath}`;
    }
    // Otherwise an inline one-liner can carry lock + timeout + logging.
    const parts: string[] = [sched];
    if (lockOn) {
      const flockFlag = lockMode === 'wait' ? `-w ${waitSeconds || '30'}` : '-n';
      parts.push(`/usr/bin/flock ${flockFlag} ${lockFile}`);
    }
    if (timeoutOn) {
      parts.push(`timeout -k ${killGrace} ${maxRuntime}`);
    }
    parts.push(command.trim() || 'your-command');
    let line = parts.join(' ');
    if (logOn) line += ` >> ${effLogPath} 2>&1`;
    return line;
  }, [
    schedule,
    retryOn,
    alertOn,
    wrapperPath,
    lockOn,
    lockMode,
    waitSeconds,
    lockFile,
    timeoutOn,
    killGrace,
    maxRuntime,
    command,
    logOn,
    effLogPath,
  ]);

  const crontabNeedsWrapper = retryOn || alertOn;

  async function copy(text: string, key: string) {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(key);
      setTimeout(() => setCopied((c) => (c === key ? null : c)), 1500);
    } catch {
      setCopied('err');
      setTimeout(() => setCopied((c) => (c === 'err' ? null : c)), 1500);
    }
  }

  const installCmd = `sudo install -m 755 safe-${jobName}.sh ${wrapperPath}`;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* ---- Controls ---- */}
      <div className="space-y-4">
        <div className={SECTION}>
          <label className={LABEL}>The command your cron job runs</label>
          <input
            className={INPUT}
            value={command}
            onChange={(e) => setCommand(e.target.value)}
            spellCheck={false}
            placeholder="rsync -a --delete /data/ /mnt/backup/data/"
          />
          <p className={HINT}>
            A single command and its arguments. For a pipeline or several
            commands, enter <code className="text-[var(--green)]">bash -c &apos;cmd1 | cmd2&apos;</code>.
          </p>
          <div className="mt-3">
            <label className={LABEL}>Job name (used for lock, log, wrapper)</label>
            <input
              className={INPUT}
              value={name}
              onChange={(e) => setName(e.target.value)}
              spellCheck={false}
              placeholder={jobName}
            />
          </div>
        </div>

        {/* Lock */}
        <div className={SECTION}>
          <Toggle on={lockOn} onChange={setLockOn} label="Lock to a single instance (flock)" />
          <p className={HINT}>
            Stops a long run from overlapping the next one and stacking copies.
          </p>
          {lockOn && (
            <div className="mt-3 space-y-3">
              <div className="flex gap-2">
                {(['skip', 'wait'] as LockMode[]).map((m) => (
                  <button
                    key={m}
                    type="button"
                    onClick={() => setLockMode(m)}
                    className={
                      'flex-1 px-3 py-2 rounded-[var(--radius)] text-sm font-[family-name:var(--font-mono)] border transition-colors ' +
                      (lockMode === m
                        ? 'border-[var(--green)] text-[var(--green)] bg-[var(--green-dim)]'
                        : 'border-[var(--border)] text-[var(--muted)] hover:text-[var(--text)]')
                    }
                  >
                    {m === 'skip' ? 'Skip if busy (-n)' : 'Wait then give up (-w)'}
                  </button>
                ))}
              </div>
              {lockMode === 'wait' && (
                <div>
                  <label className={LABEL}>Wait up to (seconds)</label>
                  <input
                    className={INPUT}
                    value={waitSeconds}
                    onChange={(e) => setWaitSeconds(e.target.value)}
                    inputMode="numeric"
                  />
                </div>
              )}
            </div>
          )}
        </div>

        {/* Timeout */}
        <div className={SECTION}>
          <Toggle on={timeoutOn} onChange={setTimeoutOn} label="Bound the runtime (timeout)" />
          <p className={HINT}>
            Kills a hung run so it can&apos;t hold the lock and jam every future run.
          </p>
          {timeoutOn && (
            <div className="mt-3 grid grid-cols-2 gap-3">
              <div>
                <label className={LABEL}>Max runtime</label>
                <input
                  className={INPUT}
                  value={maxRuntime}
                  onChange={(e) => setMaxRuntime(e.target.value)}
                  spellCheck={false}
                  placeholder="5m"
                />
              </div>
              <div>
                <label className={LABEL}>SIGKILL grace</label>
                <input
                  className={INPUT}
                  value={killGrace}
                  onChange={(e) => setKillGrace(e.target.value)}
                  spellCheck={false}
                  placeholder="20s"
                />
              </div>
            </div>
          )}
        </div>

        {/* Retry */}
        <div className={SECTION}>
          <Toggle on={retryOn} onChange={setRetryOn} label="Retry transient failures (backoff)" />
          <p className={HINT}>
            Survives a blip or a not-yet-ready dependency instead of dying on the first error.
          </p>
          {retryOn && (
            <div className="mt-3 grid grid-cols-2 gap-3">
              <div>
                <label className={LABEL}>Max attempts</label>
                <input
                  className={INPUT}
                  value={maxAttempts}
                  onChange={(e) => setMaxAttempts(e.target.value)}
                  inputMode="numeric"
                />
              </div>
              <div>
                <label className={LABEL}>Base delay (s)</label>
                <input
                  className={INPUT}
                  value={baseDelay}
                  onChange={(e) => setBaseDelay(e.target.value)}
                  inputMode="numeric"
                />
              </div>
            </div>
          )}
        </div>

        {/* Logging */}
        <div className={SECTION}>
          <Toggle on={logOn} onChange={setLogOn} label="Timestamped logging" />
          <p className={HINT}>
            Cron discards output by default. Write what happened to a file you can read.
          </p>
          {logOn && (
            <div className="mt-3">
              <label className={LABEL}>Log file</label>
              <input
                className={INPUT}
                value={logPath}
                onChange={(e) => setLogPath(e.target.value)}
                spellCheck={false}
                placeholder={effLogPath}
              />
            </div>
          )}
        </div>

        {/* Alert */}
        <div className={SECTION}>
          <Toggle on={alertOn} onChange={setAlertOn} label="Email alert on failure (mailx)" />
          <p className={HINT}>
            Sends mail only when the job fails after its retries. Requires mailx configured.
          </p>
          {alertOn && (
            <div className="mt-3">
              <label className={LABEL}>Send to</label>
              <input
                className={INPUT}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                spellCheck={false}
                placeholder="ops@example.com"
              />
            </div>
          )}
        </div>

        {/* Schedule */}
        <div className={SECTION}>
          <label className={LABEL}>Cron schedule</label>
          <input
            className={INPUT}
            value={schedule}
            onChange={(e) => setSchedule(e.target.value)}
            spellCheck={false}
            placeholder="*/5 * * * *"
          />
          <p className={HINT}>
            Need help with the expression? The{' '}
            <Link href="/tools/cron-job-builder" className="text-[var(--blue)] hover:underline">
              Cron Job Builder
            </Link>{' '}
            builds it visually.
          </p>
        </div>
      </div>

      {/* ---- Output ---- */}
      <div className="lg:sticky lg:top-6 self-start space-y-3">
        <div className="flex gap-2">
          {(['wrapper', 'crontab'] as OutputTab[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setTab(t)}
              className={
                'px-4 py-2 rounded-[var(--radius)] text-sm font-[family-name:var(--font-mono)] border transition-colors ' +
                (tab === t
                  ? 'border-[var(--green)] text-[var(--green)] bg-[var(--green-dim)]'
                  : 'border-[var(--border)] text-[var(--muted)] hover:text-[var(--text)]')
              }
            >
              {t === 'wrapper' ? `safe-${jobName}.sh` : 'crontab line'}
            </button>
          ))}
        </div>

        {tab === 'wrapper' ? (
          <div className="rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] overflow-hidden">
            <div className="flex items-center justify-between px-4 py-2 border-b border-[var(--border)] bg-[var(--bg2)]">
              <span className="font-[family-name:var(--font-mono)] text-xs text-[var(--muted)]">
                {wrapperPath}
              </span>
              <button
                type="button"
                onClick={() => copy(wrapper, 'wrapper')}
                className="font-[family-name:var(--font-mono)] text-xs px-2 py-1 rounded border border-[var(--border)] text-[var(--green)] hover:bg-[var(--green-dim)] transition-colors"
              >
                {copied === 'wrapper' ? 'copied ✓' : 'copy'}
              </button>
            </div>
            <pre className="p-4 overflow-x-auto text-[13px] leading-relaxed">
              <code className="font-[family-name:var(--font-mono)] text-[var(--text)] whitespace-pre">
                {wrapper}
              </code>
            </pre>
          </div>
        ) : (
          <div className="space-y-3">
            <div className="rounded-[var(--radius)] border border-[var(--border)] bg-[var(--bg)] overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2 border-b border-[var(--border)] bg-[var(--bg2)]">
                <span className="font-[family-name:var(--font-mono)] text-xs text-[var(--muted)]">
                  crontab -e
                </span>
                <button
                  type="button"
                  onClick={() => copy(crontab, 'crontab')}
                  className="font-[family-name:var(--font-mono)] text-xs px-2 py-1 rounded border border-[var(--border)] text-[var(--green)] hover:bg-[var(--green-dim)] transition-colors"
                >
                  {copied === 'crontab' ? 'copied ✓' : 'copy'}
                </button>
              </div>
              <pre className="p-4 overflow-x-auto text-[13px] leading-relaxed">
                <code className="font-[family-name:var(--font-mono)] text-[var(--text)] whitespace-pre">
                  {crontab}
                </code>
              </pre>
            </div>
            {crontabNeedsWrapper ? (
              <p className={HINT}>
                Retry and email-alert need the wrapper script, so this crontab line
                points at <code className="text-[var(--green)]">{wrapperPath}</code>. Install it
                first:
                <span className="block mt-2 font-[family-name:var(--font-mono)] text-[var(--text)] break-all">
                  {installCmd}
                </span>
              </p>
            ) : (
              <p className={HINT}>
                Lock and timeout inline cleanly, so no wrapper file is needed — paste this
                straight into <code className="text-[var(--green)]">crontab -e</code>. Turn on
                retry or alerting and the line switches to call a wrapper instead.
              </p>
            )}
          </div>
        )}

        {!command.trim() && (
          <p className="text-xs text-[var(--amber)] font-[family-name:var(--font-mono)]">
            Enter the command your cron job runs to generate the wrapper.
          </p>
        )}
      </div>
    </div>
  );
}
